
# Este evento ejecuta el workflow cuando hacemos push
          # 1. pull_request
          #Se ejecuta cuando se crea o modifica un Pull Request:
          #on:
          #  pull_request:
          #    branches:
          #      - main
                      #2. workflow_dispatch
                      #Permite ejecutarlo manualmente desde GitHub:
                      #on:
                      #  workflow_dispatch:
                      #on:
                      #  workflow_dispatch:
                      #   inputs:
                      #      environment:
                      #        description: "Entorno"
                      #        required: true
                      #        type: choice
                      #        options:
                      #          - development
                      #          - production
                                                  #3. schedule
                                                  #Ejecutarlo automáticamente mediante cron:
                                                  #on:
                                                  #  schedule:
                                                  #    - cron: "0 8 * * 1"
                                                  # Esto lo ejecuta cada lunes a las 08:00 UTC.
                                                                                                      # 4. push con tags
                                                                                                      # on:
                                                                                                      #   push:
                                                                                                      #     tags:
                                                                                                      #       - "v*"
                                                                                                      # Por ejemplo, se ejecutaría al crear:
                                                                                                      # v1.0.0
                                                                                                       # v2.3.1

# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        shell: bash
        run: |
          echo "Add other actions to build,"
          echo "Aquí puedo ejecutar varios comandos"
          echo "Estoy dentro del runner de GitHub"
          pwd
          ls -la
          
  build_two:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        shell: bash
        run: |
          echo "Add other actions to build,"
          echo "Aquí puedo ejecutar varios comandos"
          echo "Estoy dentro del runner de GitHub"
          pwd
          ls -la
